flowchart TD

subgraph remove_admitted_aspirants
direction TB
R0([Inicio función remove_admitted_aspirants]) --> R1
R1[/Recibir los parámetros: lista de aspirantes, lista de admitidos/] --> R2
R2[Obtener lista de admitidos por nombre] --> R3
R3[Filtrar lista de aspirantes eliminando los nombres admitidos] --> R4
R4[/Retornar la lista de aspirantes depurado/] --> R5
R5([Fin función])
end

subgraph calcular_puntaje_admision
direction TB
A2([Inicio de función calcular_puntaje_admision]) --> B2
B2[/Recibir datos del aspirante y nombre del departamento/] --> C2
C2{Selector Departamento} -- Physics --> E21 
C2 -- Mathematics --> E22
C2 -- Engineering --> E23
C2 -- Chemistry --> E24
C2 -- Biotech --> E25
C2 -- Otro --> F21

E21[Seleccionar puntajes EPH, EMA, ESP] --> G2[Calcular promedio de puntajes]
E22[Seleccionar puntajes EMA, ECS, ESP] --> G2
E23[Seleccionar puntajes EMA, ECS, EPH, ESP] --> G2
E24[Seleccionar puntajes ECH, EPH, ESP] --> G2
E25[Seleccionar puntajes EMA, ECS, ECH, ESP] --> G2

G2 --> H2[Redondear promedio a 2 decimales]
H2 --> I2[/Retornar valor calculado/]
I2 --> J2([Fin de función])
F21[/Retornar None/] --> J2
end
