flowchart TD

A[Inicio] --> B[Leer archivo CSV con datos de aspirantes]
B --> C[Solicitar número máximo de alumnos por departamento N]
C --> D[Inicializar tabla de aspirantes admitidos vacía]
D --> E[Copiar tabla original de aspirantes]
E --> F[Definir lista de opciones de admisión: OP1, OP2, OP3]

F --> G[Para cada opción en la lista de opciones]
G --> H[Para cada departamento en la lista de departamentos]
H --> I[Llamar función get_admitted_aspirants]
I --> J[Actualizar tabla de admitidos]
J --> K[Llamar función remove_admitted_aspirants para depurar aspirantes]
K --> L[Fin del ciclo por departamentos]
L --> M[Imprimir número acumulado de admitidos]
M --> N[Fin del ciclo por opciones]

N --> O[Mostrar total de aspirantes admitidos]
O --> P[Fin]
