flowchart TD

subgraph get_admitted_aspirants
direction TB
A1([Inicio función get_admitted_aspirants con parámetros departamento, orden de preferencia, tabla de admitidos, tabla de aspirantes]) --> B1
B1[Imprimir nombre del departamento] --> C1[Calcular número de admitidos actuales en el departamento]
C1 --> D1[Calcular cupos disponibles N_disponibles = N - N_admitidos]
D1 --> E1{¿N_disponibles <= 0?}
E1 -- sí --> F1[Imprimir 'Departamento sin cupo'] --> Z1[Retornar tabla de admitidos]
E1 -- no --> G1[Filtrar aspirantes que han elegido el departamento en el orden de preferencia dado]
G1 --> H1{¿Existen aspirantes en este departamento?}
H1 -- no --> I1[Imprimir 'No hay aspirantes'] --> Z1
H1 -- sí --> J1[Ordenar aspirantes por puntaje descendente]
J1 --> K1[Seleccionar N_disponibles mejores aspirantes]
K1 --> L1[Crear DataFrame con nombre, depto, puntaje, opción]
L1 --> M1[Mostrar lista de admitidos]
M1 --> N1{¿Tabla de admitidos vacía?}
N1 -- Sí --> O1[Asignar admitidos = aspirantes del depto]
O1 --> Z1
N1 -- No --> P1[Concatenar con tabla de admitidos existente]
P1 --> Z1
Z1 --> Q1([Fin de función])
end
